* Todo's for a better System:

***** Wallpapers
Add custom wallpaper Pack and push it to git.
Include: hyprpaper, hypridle

***** Hyprland Plugins ???
csgo-vulkan-fix 
hyprtrails -> Depends on Fix-Mouse-windowMove
Link: https://github.com/hyprwm/hyprland-plugins

***** ScratchPad
Link: https://github.com/hyprland-community/pyprland

***** if / else Conditions 
For better Configs without git conflicts between hosts.

***** Repo Documnetation
Better / Add Documentation for tthe Configs.
Maybe push it as public repo.



* OffTheWall's NixOs Config Install
This short Documentation should list the needed steps for a proper installation of this repo.


** Flake Install
Add the following line to /etc/nixos/configuration.nix to install flakes.

#+begin_src 
nix.settings.experimental-features = [ "nix-command" "flakes" ];
#+end_src

After the line is added. Save and close the file.

#+begin_src
cd /etc/nixos
sudo nixos-rebuild switch
#+end_src


** Home-Manager Installation
To install the Home-Manager as a stand-alone Module, execute the following code.

#+begin_src 
sudo nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
sudo nix-channel --update
sudo nix-shell '<home-manager>' -A install
#+end_src


** Clone Repository
Now we can clone the repository and run the install commands.
After that a reboot is needed.

#+begin_src 
cd ~/.config/nixos
# clone Repository
sudo nixos-rebuild --flake . switch
home-manager --flake . switch

reboot
#+end_src


** Post Install 
After a successfull install & reboot, the following commands can be used to update / install NixOs & Home-Manager Modules.

#+begin_src 
os_rebuild    # -> For updateing & rebuild NixOs configs
hm_rebuild    # -> For rebuilding Home-Manager configs
#+end_src


* Links:
***** LibrePhoenix:
- https://github.com/librephoenix/nixos-config
  
***** Awesome Hyprland
- https://github.com/hyprland-community/awesome-hyprland#plugins

***** Better graphics performance
Usefull links:
 - https://github.com/lutris/docs/blob/master/InstallingDrivers.md
 - https://nixos.wiki/wiki/AMD_GPU
