# Network
interface = "wlp0s20f3"

# Lengthen uptime output
long_uptime = true

# Lengthen shell output
long_shell = true

# Lengthen kernel output
long_kernel = true

# Long or short shell
current_shell = true

# Toggle between cores
# processor.
physical_cores = false

# Theme to choose
theme = "wally"

# Displays only the specified readouts.
# Accepted values (case-sensitive):
#   - Host
#   - Machine
#   - Kernel
#   - Distribution
#   - OperatingSystem
#   - DesktopEnvironment
#   - WindowManager
#   - Resolution
#   - Backlight
#   - Packages
#   - LocalIP
#   - Terminal
#   - Shell
#   - Uptime
#   - Processor
#   - ProcessorLoad
#   - Memory
#   - Battery
#   - GPU
#   - DiskSpace
# Example:
show = [ "Machine", "Host", "Distribution", "Resolution", "DesktopEnvironment", "Terminal", "Kernel", "LocalIP", "Processor", "ProcessorLoad", "Memory", "Battery", "Backlight", "Uptime", "Packages", "Shell", "Terminal"]